### ISSUE TITLE
Import feature broken? 

### ISSUE THREAD

**Issue by krab** [jmis/ExileCraft#18]
Also web page don't work correctly after import failure. Stats stop counts on passive nodes allocation, tooltips of nodes became broken too.

**Comment by jmis** [comment]
I just tested importing using the following link:

https://www.pathofexile.com/fullscreen-passive-skill-tree/AAAAAwMBEFgRLSycMtFEq0WdU1JVrl5dfIOCEI-mmuCnlK-b0f3fsOvu

Can you provide the URL you're using?

**Comment by krab** [comment]
http://exilecraft.org/#AAAAAwMAEFgRLSycMtFEq0WdU1JVrl5dfIOCEI+mmuCnlK+b0f3fsOvu

With no nodes allocated (fresh page) its failed and after all web page bugged.

**Comment by jmis** [comment]
Still not able to reproduce the issue.  Which browser are you running?

**Comment by krab** [comment]
Latest Firefox Release.

**Comment by krab** [comment]
Hmhm, now it works without problems. Very strange.
